name: Build and Deploy

on:
  push:
    branches:
      - main
      - fix/CI-CD

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install nodejs
        run: sudo apt install nodejs
      - name: Install npm
        run: sudo apt install npm
      #       env:
      #         CI: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: krisnadwi/lms-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker rm -f lms-frontend; \
            docker rmi krisnadwi/lms-frontend:latest; \
            docker pull krisnadwi/lms-frontend; \
            docker run -d -p 80:80 --name lms-frontend krisnadwi/lms-frontend
